FROM eclipse-temurin:25-jdk
WORKDIR /app

COPY gradlew ./
COPY gradle gradle
COPY build.gradle.kts settings.gradle.kts ./
COPY src src

RUN chmod +x gradlew
RUN ./gradlew dependencies --no-daemon --console=plain
RUN ./gradlew bootJar --no-daemon --console=plain

COPY /app/build/libs/multiplayer-paint-1.0.0.jar ./

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/multiplayer-paint-1.0.0.jar"]